require('Libraries/libraries')
require('Ninguem_Extras/ngm_functions')
require('Ninguem_Extras/game_state')
require('Ninguem_Extras/font')
require('Language/lang')
require('World/myWorld')
require('World/Maps/load-maps')
require('Load_Sprites/load-sprites')
--require('Spawn/Enemys/zombie')
require('Spawn/loot/bau')
require('Spawn/Map/muro')
--require('Spawn/Map/arvore')
require('Spawn/Map/background')
require('Player/player')
require('Player/Inventario/moedas')
require('Player/Inventario/bag')
require('config')
require('Ninguem_Extras/tutorial')
require('Spawn/loot/dropCoin')
require('Spawn/loot/bronzeCoin')
require('Spawn/loot/silverCoin')
require('Spawn/loot/goldCoin')

--Last loads forever
require('main_require/load_main')
require('main_require/update_main')
require('main_require/draw_main')
